apiVersion: v2
name: regproc-salt
description: A Helm chart to generate keys for Kernel
type: application
version: 1.3.0-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - regproc-salt
  - regproc
maintainers:
  - email: info@mosip.io
    name: MOSIP
