apiVersion: v2
name: notifier
description: A Helm chart for MOSIP Notifier module
type: application
version: 1.3.0-beta.3
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - notifier
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
