apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-server.fullname" . }}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $index, $repo := .Values.spring_profiles.spring_compositeRepos }}
  {{- if $repo.token }}
  github-token-{{ $index }}: {{ $repo.token | quote }}
  {{- else }}
  github-token-{{ $index }}: ""
  {{- end }}
  {{- end }}
